# Generated by Django 3.2 on 2021-11-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('version', models.FloatField()),
                ('placa', models.CharField(max_length=25)),
                ('kilometraje', models.IntegerField()),
            ],
        ),
    ]
